# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'database_created.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_database_created(object):
    def setupUi(self, database_created):
        database_created.setObjectName("database_created")
        database_created.resize(400, 299)
        database_created.setStyleSheet("background-color: rgb(213, 221, 255);")
        self.pushButton = QtWidgets.QPushButton(database_created)
        self.pushButton.setGeometry(QtCore.QRect(160, 170, 75, 23))
        self.pushButton.setStyleSheet("background-color: rgb(255, 250, 189);")
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(database_created)
        self.textEdit.setGeometry(QtCore.QRect(20, 60, 361, 71))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(database_created)
        QtCore.QMetaObject.connectSlotsByName(database_created)

    def retranslateUi(self, database_created):
        _translate = QtCore.QCoreApplication.translate
        database_created.setWindowTitle(_translate("database_created", "Dialog"))
        self.pushButton.setText(_translate("database_created", "ОК"))
        self.textEdit.setHtml(_translate("database_created", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">База данных создана успешно</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    database_created = QtWidgets.QDialog()
    ui = Ui_database_created()
    ui.setupUi(database_created)
    database_created.show()
    sys.exit(app.exec_())
