# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from data_functions import delete_data
from database_deleted_gui import Ui_database_deleted


class Ui_DeleteWindow(object):
    def setupUi(self, DeleteWindow):
        DeleteWindow.setObjectName("DeleteWindow")
        DeleteWindow.resize(800, 600)
        DeleteWindow.setStyleSheet("background-color: rgb(213, 221, 255);")
        self.centralwidget = QtWidgets.QWidget(DeleteWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 110, 401, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(290, 250, 251, 51))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 250, 189);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit.setFrame(True)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(360, 340, 101, 41))
        self.deleteButton.setStyleSheet("background-color: rgb(255, 250, 189);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.deleteButton.setObjectName("deleteButton")
        DeleteWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DeleteWindow)
        self.statusbar.setObjectName("statusbar")
        DeleteWindow.setStatusBar(self.statusbar)
        self.deleteButton.clicked.connect(self.delete_db)

        self.retranslateUi(DeleteWindow)
        QtCore.QMetaObject.connectSlotsByName(DeleteWindow)

    def delete_db(self):
        delete_data(self.lineEdit.text())
        database_deleted = QtWidgets.QDialog()
        ui = Ui_database_deleted()
        ui.setupUi(database_deleted)
        database_deleted.show()
        database_deleted.exec_()

    def retranslateUi(self, DeleteWindow):
        _translate = QtCore.QCoreApplication.translate
        DeleteWindow.setWindowTitle(_translate("DeleteWindow", "MainWindow"))
        self.label.setText(_translate("DeleteWindow", "Введите имя базы данных"))
        self.lineEdit.setText(_translate("DeleteWindow", "Имя"))
        self.deleteButton.setText(_translate("DeleteWindow", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DeleteWindow = QtWidgets.QMainWindow()
    ui = Ui_DeleteWindow()
    ui.setupUi(DeleteWindow)
    DeleteWindow.show()
    sys.exit(app.exec_())
