# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_data_name.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from data_functions import create_data
from database_created_gui import Ui_database_created


class Ui_NameMainWindow(object):
    def setupUi(self, NameMainWindow):
        NameMainWindow.setObjectName("MainWindow")
        NameMainWindow.resize(800, 600)
        NameMainWindow.setStyleSheet("background-color: rgb(213, 221, 255);")
        self.centralwidget = QtWidgets.QWidget(NameMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 110, 401, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(290, 250, 251, 51))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 250, 189);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit.setFrame(True)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(360, 340, 101, 41))
        self.pushButton.setStyleSheet("background-color: rgb(255, 250, 189);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        NameMainWindow.setCentralWidget(self.centralwidget)
        ###############################################################
        self.pushButton.clicked.connect(self.create_db)
        self.statusbar = QtWidgets.QStatusBar(NameMainWindow)
        self.statusbar.setObjectName("statusbar")
        NameMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(NameMainWindow)
        QtCore.QMetaObject.connectSlotsByName(NameMainWindow)

    def create_db(self):
        create_data(self.lineEdit.text())
        database_created = QtWidgets.QDialog()
        ui = Ui_database_created()
        ui.setupUi(database_created)
        database_created.show()
        database_created.exec_()


    def retranslateUi(self, NameMainWindow):
        _translate = QtCore.QCoreApplication.translate
        NameMainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Введите имя базы данных"))
        self.lineEdit.setText(_translate("MainWindow", "Имя"))
        self.pushButton.setText(_translate("MainWindow", "Создать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NameMainWindow = QtWidgets.QMainWindow()
    ui = Ui_NameMainWindow()
    ui.setupUi(NameMainWindow)
    NameMainWindow.show()
    sys.exit(app.exec_())
