# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OpenWindow(object):
    def setupUi(self, OpenWindow):
        OpenWindow.setObjectName("OpenWindow")
        OpenWindow.resize(800, 600)
        OpenWindow.setStyleSheet("background-color: rgb(213, 221, 255);")
        self.centralwidget = QtWidgets.QWidget(OpenWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 110, 401, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(290, 250, 251, 51))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 250, 189);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit.setFrame(True)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(360, 340, 101, 41))
        self.deleteButton.setStyleSheet("background-color: rgb(255, 250, 189);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.deleteButton.setObjectName("deleteButton")
        OpenWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(OpenWindow)
        self.statusbar.setObjectName("statusbar")
        OpenWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OpenWindow)
        QtCore.QMetaObject.connectSlotsByName(OpenWindow)

    def retranslateUi(self, OpenWindow):
        _translate = QtCore.QCoreApplication.translate
        OpenWindow.setWindowTitle(_translate("OpenWindow", "MainWindow"))
        self.label.setText(_translate("OpenWindow", "Введите имя базы данных"))
        self.lineEdit.setText(_translate("OpenWindow", "Имя"))
        self.deleteButton.setText(_translate("OpenWindow", "Открыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OpenWindow = QtWidgets.QMainWindow()
    ui = Ui_OpenWindow()
    ui.setupUi(OpenWindow)
    OpenWindow.show()
    sys.exit(app.exec_())
